[package]
name = "handler"
version = "0.1.0"
authors = ["Damien Pontifex <damien.pontifex@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = { version = "1", features = ["derive"] }